-- Criando um Schema
CREATE SCHEMA DM

-- Criando o banco de dados
CREATE DATABASE DM_TSE_ELEICAO


-- Criando dimensões
CREATE TABLE DM.DIM_TIPO_ELEICAO
(
	SK_TIPO_ELEICAO		INT		PRIMARY KEY IDENTITY (200000, 1),
	CD_SO_TIPO_ELEICAO	INT, --CD = CODIGO / SO = SISTEMA ORIGEM
	NM_TIPO_ELEICAO		VARCHAR(250)
)

CREATE TABLE DM.DIM_ELEICAO
(
	SK_ELEICAO		INT		PRIMARY KEY IDENTITY (300000, 1),
	CD_SO_ELEICAO 	INT,
	DS_ELEICAO		VARCHAR(250),
	NR_TURNO		TINYINT,
	TP_ABRANGENCIA	VARCHAR(250)
)

CREATE TABLE DM.DIM_LOCALIDADE
(
	SK_LOCALIDADE	INT		PRIMARY KEY IDENTITY (400000, 1),
	SG_UF			CHAR(2),
	NM_UF			VARCHAR(250),
	CD_SO_MUNICIPIO	INT,
	NM_MUNICIPIO	VARCHAR(250),
	NR_ZONA			INT

)

CREATE TABLE DM.DIM_CARGO
(
	SK_CARGO		INT		PRIMARY KEY IDENTITY (500000, 1),
	CD_SO_CARGO		INT,
	DS_CARGO		VARCHAR(250)
)

CREATE TABLE DM.DIM_CANDIDATO
(
	SK_CANDIDATO		INT		PRIMARY KEY IDENTITY (10000000, 1),
	CD_SO_CANDIDATO		INT,
	NR_CANDIDATO		INT,
	NM_CANDIDATO		VARCHAR(250),
	NM_URNA_CANDIDATO	VARCHAR(250),
	NM_SOCIAL_CANDIDATO VARCHAR(250)

)

CREATE TABLE DM.DIM_CANDIDATURA
(
	SK_CANDIDATURA					INT		PRIMARY KEY IDENTITY (600000, 1),
	CD_SO_SITUACAO_CANDIDATURA		INT,
	DS_SITUACAO_CANDIDATURA			VARCHAR(250),
	CD_SO_DETALHE_SITUACAO_CAND		INT,
	DS_DETALHE_SITUACAO_CAND		VARCHAR(250)
)

CREATE TABLE DM.DIM_AGREMIACAO
(
	SK_AGREMIACAO				INT		PRIMARY KEY	IDENTITY (700000, 1),
	CD_SO_AGREMIACAO			INT,
	NM_AGREMIACAO				VARCHAR(250),
	SG_AGREMIACAO				VARCHAR(250),
	NM_COMPOSICAO_AGREMIACAO	VARCHAR(250),
	TP_AGREMIACAO				VARCHAR(250)
)

CREATE TABLE DM.DIM_SITUACAO_CANDIDATO
(
	SK_SITUACAO_CANDIDATO		INT		PRIMARY KEY	IDENTITY (800000, 1),
	CD_SO_SITUACAO_CANDIDATO	INT,
	NM_SITUACAO_CANDIDATO		VARCHAR(250)
)

CREATE TABLE DM.DIM_PARTIDO
(
	SK_PARTIDO		INT		PRIMARY KEY IDENTITY (900000, 1),
	CD_SO_PARTIDO	INT,
	SG_PARTIDO		VARCHAR(250),
	NM_PARTIDO		VARCHAR(250)
)

CREATE TABLE DM.DIM_CALENDARIO
(
	SK_TEMPO						INT		PRIMARY KEY,
	DT_TEMPO						DATETIME,
	NR_ANO							SMALLINT,
	NR_MES							TINYINT,
	NR_DIA							TINYINT,
	NM_MES							VARCHAR(250),
	NM_MES_ABREVIADO				CHAR(3),
	NM_DIA_SEMANA					VARCHAR(250),
	NM_DIA_SEMANA_ABREVIDADO		CHAR(3)
)